# Generated by Django 6.0.1 on 2026-01-15 00:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_alter_analysis_body"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        blank=True,
                        help_text="Large heading displayed at the top of the page",
                        max_length=255,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        blank=True, help_text="Subtitle or description below the hero title"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("paragraph", 1),
                            ("image", 2),
                            ("data_visualization", 16),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "form_classname": "full title",
                                    "icon": "title",
                                    "label": "Heading",
                                },
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"icon": "pilcrow", "label": "Rich Text Paragraph"},
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"icon": "image", "label": "Image"},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Top Donors",
                                    "help_text": "Heading displayed above the leaderboard",
                                },
                            ),
                            4: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 10,
                                    "help_text": "Number of donors to display (5-50)",
                                    "max_value": 50,
                                    "min_value": 5,
                                },
                            ),
                            5: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Show filter controls alongside the leaderboard",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 3), ("limit", 4), ("show_filter_panel", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Donor Concentration",
                                    "help_text": "Heading displayed above the chart",
                                },
                            ),
                            8: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Optional explanatory text displayed below the chart",
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 7), ("description", 8)]],
                                {},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Filters",
                                    "help_text": "Heading displayed above filters",
                                },
                            ),
                            11: ("wagtail.blocks.StructBlock", [[("title", 10)]], {}),
                            12: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "help_text": "Actor ID from the database (find in /django-admin/datafetch/actor/)"
                                },
                            ),
                            13: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Use compact single-line layout",
                                    "required": False,
                                },
                            ),
                            14: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Show donation statistics",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("actor_id", 12), ("compact", 13), ("show_stats", 14)]],
                                {},
                            ),
                            16: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("leaderboard", 6),
                                        ("concentration_chart", 9),
                                        ("filter_panel", 11),
                                        ("actor_card", 15),
                                    ]
                                ],
                                {"icon": "snippet", "label": "Data Visualization"},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
