# Generated by Django 6.0.1 on 2026-01-15 01:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_homepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1), ("image", 2), ("data_visualization", 19)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title", "icon": "title", "label": "Heading"},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "pilcrow", "label": "Rich Text Paragraph"},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"icon": "image", "label": "Image"},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional heading displayed above the metrics grid",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "/api/v2/aggregates/stats/",
                            "help_text": "API endpoint for statistics (usually leave as default)",
                        },
                    ),
                    5: ("wagtail.blocks.StructBlock", [[("title", 3), ("api_url", 4)]], {}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Top Donors",
                            "help_text": "Heading displayed above the leaderboard",
                        },
                    ),
                    7: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 10,
                            "help_text": "Number of donors to display (5-50)",
                            "max_value": 50,
                            "min_value": 5,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show filter controls alongside the leaderboard",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("limit", 7), ("show_filter_panel", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Donor Concentration",
                            "help_text": "Heading displayed above the chart",
                        },
                    ),
                    11: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional explanatory text displayed below the chart",
                            "required": False,
                        },
                    ),
                    12: ("wagtail.blocks.StructBlock", [[("title", 10), ("description", 11)]], {}),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Filters", "help_text": "Heading displayed above filters"},
                    ),
                    14: ("wagtail.blocks.StructBlock", [[("title", 13)]], {}),
                    15: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Actor ID from the database (find in /django-admin/datafetch/actor/)"
                        },
                    ),
                    16: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Use compact single-line layout",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show donation statistics",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("actor_id", 15), ("compact", 16), ("show_stats", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("stats_grid", 5),
                                ("leaderboard", 9),
                                ("concentration_chart", 12),
                                ("filter_panel", 14),
                                ("actor_card", 18),
                            ]
                        ],
                        {"icon": "snippet", "label": "Data Visualization"},
                    ),
                },
            ),
        ),
    ]
