"""
Django settings for undertheinfluence project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from os.path import dirname, join, realpath
from decouple import config, Csv

BASE_DIR = realpath(dirname(dirname(__file__)))
PROJECT_DIR = join(BASE_DIR, 'undertheinfluence')

# Load configuration from environment variables
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

BASE_URL = config('BASE_URL', default='http://localhost:8000')

# Django 3.2+ requires DEFAULT_AUTO_FIELD setting
# Using AutoField to maintain compatibility with existing migrations
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'cms',
    'datafetch',
    'appc_redirect',
    'api',

    # 'bootstrap_admin',  # Removed - not compatible with Django 2.0+
    'corsheaders',  # CORS support for frontend on different port
    'rest_framework',
    'django_filters',  # Django Filter for API v2
    'drf_spectacular',  # OpenAPI schema generation
    'django_vite',  # Vite integration for Islands Architecture frontend

    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.admin',
    'wagtail',

    'modelcluster',
    'compressor',
    'taggit',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'wagtail.contrib.legacy.sitemiddleware.SiteMiddleware',  # Moved to legacy in Wagtail 2.15
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ROOT_URLCONF = 'undertheinfluence.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            join(PROJECT_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# BOOTSTRAP_ADMIN_SIDEBAR_MENU = True  # Removed - bootstrap-admin not compatible with Django 2.0+

WSGI_APPLICATION = 'undertheinfluence.wsgi.application'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# The email address that will be displayed on the site as the contact
# email for all support requests, and so on:
SUPPORT_EMAIL = config('SUPPORT_EMAIL', default='')

# The From = address for error emails
SERVER_EMAIL = config('SERVER_EMAIL', default='')

# The From = address for all emails except error emails
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='')

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

if config('DATABASE_SYSTEM', default='sqlite') == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE':   'django.db.backends.postgresql',
            'NAME':     'undertheinfluence', # Explicitly set to match the created database
            'USER':     config('UTI_DB_USER', default='uti'),
            'PASSWORD': config('UTI_DB_PASS', default=''),
            'HOST':     config('UTI_DB_HOST', default='localhost'),
            'PORT':     config('UTI_DB_PORT', default='5432'),
        }
    }
    # PostgreSQL timezone workaround removed - no longer needed in Django 3.2+
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': join(BASE_DIR, 'db.sqlite3'),
        }
    }

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)

STATICFILES_DIRS = (
    join(PROJECT_DIR, 'static'),
)

STATIC_ROOT = join(BASE_DIR, 'static')
STATIC_URL = '/static/'

# Vite integration for Islands Architecture frontend
DJANGO_VITE = {
    'default': {
        'dev_mode': DEBUG,
        'dev_server_host': config('DJANGO_VITE_DEV_SERVER_HOST', default='localhost'),
        'dev_server_port': 5173,
        'manifest_path': join(BASE_DIR, 'static', 'dist', 'manifest.json'),
    }
}

MEDIA_ROOT = join(BASE_DIR, 'media')
MEDIA_URL = '/media/'



# Wagtail settings

WAGTAIL_SITE_NAME = "UnderTheInfluence"

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "SAMEORIGIN"  # for the wagtail toolbar
CSRF_COOKIE_HTTPONLY = True

# CORS settings (for Astro frontend on different port)
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:4321,http://127.0.0.1:4321',
    cast=Csv()
)
CORS_ALLOW_CREDENTIALS = True

# Django REST Framework settings
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10,
    # Add filter backends for API v2
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    # OpenAPI schema generation
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular settings for OpenAPI schema generation
SPECTACULAR_SETTINGS = {
    'TITLE': 'UnderTheInfluence API',
    'DESCRIPTION': """
    REST API for exploring political influence in the UK through donations and lobbying relationships.

    ## Features
    - **Aggregates**: Top donors, top recipients, network statistics, party donations, dual influence
    - **Actor Details**: Individual politicians and organizations with relationship history
    - **Temporal Queries**: View historical data with ?at_date= parameter
    - **Advanced Analytics**: Donor concentration metrics, Gini coefficients, HHI analysis

    ## Data Sources
    Data is aggregated from Electoral Commission, ParlParse, APPC, and other public sources.
    """,
    'VERSION': '2.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/v2/',
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
    },
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': 'Development server'},
    ],
}

# TheyWorkForYou API key
TWFY_API_KEY = config('TWFY_API_KEY', default='')

# Email addresses that error emails are sent to when DEBUG = False
# Format: "Name <email>, Name <email>"
ADMINS_STR = config('ADMINS', default='')
if ADMINS_STR:
    # Parse comma-separated admin list
    ADMINS = [tuple(admin.strip().split('<')) for admin in ADMINS_STR.split(',') if admin.strip()]
    ADMINS = [(name.strip(), email.strip(' >')) for name, email in ADMINS]
else:
    ADMINS = []
