"""
Django settings for undertheinfluence project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from os.path import dirname, join, realpath
from decouple import config, Csv

BASE_DIR = realpath(dirname(dirname(__file__)))
PROJECT_DIR = join(BASE_DIR, 'undertheinfluence')

# Load configuration from environment variables
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

BASE_URL = config('BASE_URL', default='http://localhost:8000')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'cms',
    'datafetch',
    'appc_redirect',
    'api',

    'bootstrap_admin',
    'rest_framework',
    'djangobower',

    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.admin',
    'wagtail.core',

    'modelcluster',
    'compressor',
    'taggit',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'wagtail.core.middleware.SiteMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ROOT_URLCONF = 'undertheinfluence.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            join(PROJECT_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

BOOTSTRAP_ADMIN_SIDEBAR_MENU = True

WSGI_APPLICATION = 'undertheinfluence.wsgi.application'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# The email address that will be displayed on the site as the contact
# email for all support requests, and so on:
SUPPORT_EMAIL = config('SUPPORT_EMAIL', default='')

# The From = address for error emails
SERVER_EMAIL = config('SERVER_EMAIL', default='')

# The From = address for all emails except error emails
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='')

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

if config('DATABASE_SYSTEM', default='sqlite') == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE':   'django.db.backends.postgresql',
            'NAME':     config('UTI_DB_NAME', default='undertheinfluence'),
            'USER':     config('UTI_DB_USER', default='uti'),
            'PASSWORD': config('UTI_DB_PASS', default=''),
            'HOST':     config('UTI_DB_HOST', default='localhost'),
            'PORT':     config('UTI_DB_PORT', default='5432'),
        }
    }

    # Workaround for Django 1.11 PostgreSQL timezone check bug
    # The database IS set to UTC, but Django's check is overly strict
    # Replace the problematic utc_tzinfo_factory function with one that works
    from django.db.backends.postgresql import utils
    from psycopg2.tz import FixedOffsetTimezone

    def utc_tzinfo_factory(offset):
        """Fixed version that doesn't assert on timezone"""
        if offset != 0:
            # If not UTC, use the default behavior
            return FixedOffsetTimezone(offset=offset, name=None)
        # For UTC (offset 0), return None (Django's expected behavior)
        return None

    utils.utc_tzinfo_factory = utc_tzinfo_factory
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': join(BASE_DIR, 'db.sqlite3'),
        }
    }

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
    'djangobower.finders.BowerFinder',
)

STATICFILES_DIRS = (
    join(PROJECT_DIR, 'static'),
)

STATIC_ROOT = join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Django-bower settings
BOWER_COMPONENTS_ROOT = BASE_DIR

BOWER_INSTALLED_APPS = (
    'jquery#2.1.1',
    'bootstrap',
    'bootstrap-material-design',
    'bootstrap-table',
    'moment',
)

# Wagtail settings

WAGTAIL_SITE_NAME = "UnderTheInfluence"

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "SAMEORIGIN"  # for the wagtail toolbar
CSRF_COOKIE_HTTPONLY = True

# Django REST Framework settings
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10,
}

# TheyWorkForYou API key
TWFY_API_KEY = config('TWFY_API_KEY', default='')

# Email addresses that error emails are sent to when DEBUG = False
# Format: "Name <email>, Name <email>"
ADMINS_STR = config('ADMINS', default='')
if ADMINS_STR:
    # Parse comma-separated admin list
    ADMINS = [tuple(admin.strip().split('<')) for admin in ADMINS_STR.split(',') if admin.strip()]
    ADMINS = [(name.strip(), email.strip(' >')) for name, email in ADMINS]
else:
    ADMINS = []
