# Generated by Django 4.0.10 on 2026-01-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('datafetch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='actor',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
