# Generated by Django 6.0.1 on 2026-01-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datafetch', '0002_alter_actor_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
    ]
