# Generated by Django 6.0.1 on 2026-01-14 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafetch', '0003_alter_actor_options_alter_organization_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='canonical_agency',
            field=models.ForeignKey(blank=True, help_text='Resolved canonical agency (set by entity resolution system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_consulting_clients', to='datafetch.actor'),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='canonical_client',
            field=models.ForeignKey(blank=True, help_text='Resolved canonical client (set by entity resolution system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_consulting_agencies', to='datafetch.actor'),
        ),
        migrations.AddField(
            model_name='donation',
            name='canonical_donor',
            field=models.ForeignKey(blank=True, help_text='Resolved canonical donor (set by entity resolution system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_donated_to', to='datafetch.actor'),
        ),
        migrations.AddField(
            model_name='donation',
            name='canonical_recipient',
            field=models.ForeignKey(blank=True, help_text='Resolved canonical recipient (set by entity resolution system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_received_donations_from', to='datafetch.actor'),
        ),
        migrations.AlterField(
            model_name='consultancy',
            name='agency',
            field=models.ForeignKey(help_text='Original agency from data source (never modified)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulting_clients', to='datafetch.actor'),
        ),
        migrations.AlterField(
            model_name='consultancy',
            name='client',
            field=models.ForeignKey(help_text='Original client from data source (never modified)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulting_agencies', to='datafetch.actor'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(help_text='Original donor from data source (never modified)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donated_to', to='datafetch.actor'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='recipient',
            field=models.ForeignKey(help_text='Original recipient from data source (never modified)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations_from', to='datafetch.actor'),
        ),
    ]
