# Generated by Django 6.0.1 on 2026-01-14 13:38

import datafetch.models.popolo.behaviors
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafetch', '0004_consultancy_canonical_agency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(blank=True, help_text='The date when the validity of the item starts', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Date has wrong format', regex='^[0-9]{4}(-[0-9]{2}){0,2}$'), datafetch.models.popolo.behaviors.validate_partial_date], verbose_name='start date')),
                ('end_date', models.CharField(blank=True, help_text='The date when the validity of the item ends', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Date has wrong format', regex='^[0-9]{4}(-[0-9]{2}){0,2}$'), datafetch.models.popolo.behaviors.validate_partial_date], verbose_name='end date')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='creation time')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='last modification time')),
                ('role', models.CharField(blank=True, help_text="Role within the party (e.g., 'Leader', 'Deputy Leader', 'Member')", max_length=128, verbose_name='role')),
                ('party', models.ForeignKey(help_text="The political party (must have classification='Political Party')", limit_choices_to={'classification': 'Political Party'}, on_delete=django.db.models.deletion.CASCADE, related_name='party_members', to='datafetch.organization')),
                ('person', models.ForeignKey(help_text='The person who is a member of the political party', on_delete=django.db.models.deletion.CASCADE, related_name='party_memberships', to='datafetch.person')),
            ],
            options={
                'verbose_name': 'Party Membership',
                'verbose_name_plural': 'Party Memberships',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['person', 'start_date', 'end_date'], name='datafetch_p_person__2ec117_idx'), models.Index(fields=['party', 'start_date'], name='datafetch_p_party_i_05f003_idx')],
            },
        ),
    ]
