# Generated by Django 6.0.1 on 2026-01-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('datafetch', '0005_partymembership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='othername',
            options={'verbose_name': 'Other Name', 'verbose_name_plural': 'Other Names'},
        ),
        migrations.AddField(
            model_name='othername',
            name='alias_type',
            field=models.CharField(choices=[('strong', 'Strong Alias'), ('weak', 'Weak Alias')], default='weak', help_text='Strong: High-confidence variant (abbreviations, official name changes). Weak: Low-confidence variant (normalization, fuzzy matching).', max_length=10, verbose_name='alias type'),
        ),
        migrations.AlterField(
            model_name='othername',
            name='note',
            field=models.CharField(blank=True, help_text="A note, e.g. 'Birth name', 'Common abbreviation', 'Former name'", max_length=1024, verbose_name='note'),
        ),
        migrations.AddIndex(
            model_name='othername',
            index=models.Index(fields=['name', 'alias_type'], name='datafetch_o_name_42696e_idx'),
        ),
    ]
