# Generated by Django 6.0.1 on 2026-01-14 13:57

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datafetch", "0006_alter_othername_options_othername_alias_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActorResolution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="creation time",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modification time",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Confidence score (0.0-1.0) based on match quality"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("auto_merge", "Auto-Merge (Identifier Match)"),
                            ("review", "Requires Review"),
                            ("suggest", "Suggestion Only"),
                            ("ignore", "Ignore (Low Confidence)"),
                        ],
                        help_text="Recommended action based on confidence level",
                        max_length=15,
                    ),
                ),
                (
                    "match_reason",
                    models.CharField(
                        choices=[
                            ("identifier", "External Identifier Match"),
                            ("strong_alias", "Strong Alias Match"),
                            ("weak_alias", "Weak Alias Match"),
                            ("fuzzy", "Fuzzy Name Match"),
                        ],
                        help_text="What matched (identifier, strong alias, weak alias, fuzzy)",
                        max_length=20,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved - Merge"),
                            ("rejected", "Rejected - Not Duplicate"),
                        ],
                        default="pending",
                        help_text="Whether this has been reviewed and approved/rejected",
                        max_length=10,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, help_text="When this was reviewed", null=True),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about why this was approved/rejected"
                    ),
                ),
                (
                    "actor1",
                    models.ForeignKey(
                        help_text="First actor in potential duplicate pair",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolutions_as_actor1",
                        to="datafetch.actor",
                    ),
                ),
                (
                    "actor2",
                    models.ForeignKey(
                        help_text="Second actor in potential duplicate pair",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolutions_as_actor2",
                        to="datafetch.actor",
                    ),
                ),
                (
                    "canonical_actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The canonical actor to use (typically the one with more data)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolutions_as_canonical",
                        to="datafetch.actor",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who reviewed this resolution",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Actor Resolution",
                "verbose_name_plural": "Actor Resolutions",
                "ordering": ["-confidence", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["review_status", "-confidence"],
                        name="datafetch_a_review__cfd298_idx",
                    ),
                    models.Index(
                        fields=["actor1", "review_status"], name="datafetch_a_actor1__f8b28f_idx"
                    ),
                    models.Index(
                        fields=["actor2", "review_status"], name="datafetch_a_actor2__0e1d42_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("actor1", "actor2"), name="unique_actor_pair")
                ],
            },
        ),
    ]
