# Generated by Django 6.0.1 on 2026-01-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datafetch", "0007_actorresolution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consultancy",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Consultancy",
                "verbose_name_plural": "Consultancies",
            },
        ),
        migrations.AlterModelOptions(
            name="donation",
            options={
                "ordering": ["-received_date"],
                "verbose_name": "Donation",
                "verbose_name_plural": "Donations",
            },
        ),
        migrations.AddIndex(
            model_name="consultancy",
            index=models.Index(fields=["client", "-start_date"], name="consultancy_client_idx"),
        ),
        migrations.AddIndex(
            model_name="consultancy",
            index=models.Index(fields=["agency", "-start_date"], name="consultancy_agency_idx"),
        ),
        migrations.AddIndex(
            model_name="consultancy",
            index=models.Index(
                fields=["canonical_client", "-start_date"], name="consultancy_canon_client_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultancy",
            index=models.Index(
                fields=["canonical_agency", "-start_date"], name="consultancy_canon_agency_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultancy",
            index=models.Index(fields=["start_date"], name="consultancy_start_idx"),
        ),
        migrations.AddIndex(
            model_name="consultancy",
            index=models.Index(fields=["end_date"], name="consultancy_end_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["donor", "-received_date"], name="donation_donor_date_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["recipient", "-received_date"], name="donation_recip_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["donor", "-value"], name="donation_donor_val_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["recipient", "-value"], name="donation_recip_val_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["received_date"], name="donation_date_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["canonical_donor", "-received_date"], name="donation_canon_donor_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["canonical_recipient", "-received_date"], name="donation_canon_recip_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["-value"], name="donation_value_idx"),
        ),
    ]
