# Generated by Django 6.0.1 on 2026-01-21 13:44

import datafetch.models.popolo.behaviors
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datafetch", "0008_alter_consultancy_options_alter_donation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinisterialMeeting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "start_date",
                    models.CharField(
                        blank=True,
                        help_text="The date when the validity of the item starts",
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Date has wrong format", regex="^[0-9]{4}(-[0-9]{2}){0,2}$"
                            ),
                            datafetch.models.popolo.behaviors.validate_partial_date,
                        ],
                        verbose_name="start date",
                    ),
                ),
                (
                    "end_date",
                    models.CharField(
                        blank=True,
                        help_text="The date when the validity of the item ends",
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Date has wrong format", regex="^[0-9]{4}(-[0-9]{2}){0,2}$"
                            ),
                            datafetch.models.popolo.behaviors.validate_partial_date,
                        ],
                        verbose_name="end date",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="creation time",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modification time",
                    ),
                ),
                ("meeting_date", models.DateField(help_text="Date the meeting took place")),
                (
                    "purpose",
                    models.TextField(blank=True, help_text="Purpose or subject of the meeting"),
                ),
                (
                    "external_actor_name_raw",
                    models.CharField(
                        help_text="Preserve original external actor name exactly as published",
                        max_length=512,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, help_text="URL to the GOV.UK transparency publication"
                    ),
                ),
                (
                    "source_quarter",
                    models.CharField(
                        blank=True, help_text="Publication quarter (e.g., '2024-Q1')", max_length=7
                    ),
                ),
                (
                    "canonical_external_actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolved canonical actor (set by entity resolution system)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canonical_ministerial_meetings",
                        to="datafetch.actor",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="The government department publishing this meeting record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ministerial_meetings",
                        to="datafetch.organization",
                    ),
                ),
                (
                    "external_actor",
                    models.ForeignKey(
                        help_text="Original external actor from data source (never modified)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ministerial_meetings_as_external",
                        to="datafetch.actor",
                    ),
                ),
                (
                    "minister",
                    models.ForeignKey(
                        help_text="The minister who attended the meeting",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ministerial_meetings_as_minister",
                        to="datafetch.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ministerial Meeting",
                "verbose_name_plural": "Ministerial Meetings",
                "ordering": ["-meeting_date"],
                "indexes": [
                    models.Index(fields=["minister", "-meeting_date"], name="meeting_minister_idx"),
                    models.Index(
                        fields=["external_actor", "-meeting_date"], name="meeting_external_idx"
                    ),
                    models.Index(fields=["department", "-meeting_date"], name="meeting_dept_idx"),
                    models.Index(
                        fields=["canonical_external_actor", "-meeting_date"],
                        name="meeting_canon_idx",
                    ),
                    models.Index(fields=["meeting_date"], name="meeting_date_idx"),
                    models.Index(fields=["source_quarter"], name="meeting_quarter_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "minister",
                            "external_actor_name_raw",
                            "meeting_date",
                            "department",
                        ),
                        name="unique_ministerial_meeting",
                    )
                ],
            },
        ),
    ]
