# Generated by Django 6.0.1 on 2026-01-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datafetch", "0009_ministerialmeeting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ministerialmeeting",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="URL to the GOV.UK transparency publication", null=True
            ),
        ),
    ]
