# Generated by Django 6.0.1 on 2026-01-21 14:19

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datafetch", "0010_alter_ministerialmeeting_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="ministerialmeeting",
            name="is_roundtable",
            field=models.BooleanField(
                default=False,
                help_text="True if meeting has multiple attendees (comma-separated in source)",
            ),
        ),
        migrations.AlterField(
            model_name="actorresolution",
            name="match_reason",
            field=models.CharField(
                choices=[
                    ("identifier", "External Identifier Match"),
                    ("exact", "Exact Name Match"),
                    ("known_alias", "Known Alias (Manual Mapping)"),
                    ("substring", "Substring Match"),
                    ("strong_alias", "Strong Alias Match"),
                    ("weak_alias", "Weak Alias Match"),
                    ("fuzzy", "Fuzzy Name Match"),
                    ("acronym", "Acronym Match"),
                ],
                help_text="What matched (identifier, strong alias, weak alias, fuzzy)",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MeetingAttendee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="creation time",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modification time",
                    ),
                ),
                (
                    "actor_name_raw",
                    models.CharField(
                        help_text="Original name as it appeared in source data", max_length=512
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="Original actor from data source (never modified)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_attendances",
                        to="datafetch.actor",
                    ),
                ),
                (
                    "canonical_actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolved canonical actor (set by entity resolution system)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canonical_meeting_attendances",
                        to="datafetch.actor",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        help_text="The meeting this actor attended",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="datafetch.ministerialmeeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Attendee",
                "verbose_name_plural": "Meeting Attendees",
                "ordering": ["meeting", "actor"],
                "indexes": [
                    models.Index(
                        fields=["meeting", "actor"], name="datafetch_m_meeting_df1ff1_idx"
                    ),
                    models.Index(fields=["actor"], name="datafetch_m_actor_i_442164_idx"),
                    models.Index(fields=["canonical_actor"], name="datafetch_m_canonic_102507_idx"),
                    models.Index(
                        fields=["canonical_actor", "meeting"], name="datafetch_m_canonic_ea0fd6_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("meeting", "actor_name_raw"), name="unique_meeting_attendee"
                    )
                ],
            },
        ),
    ]
