# Generated by Django 6.0.1 on 2026-01-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datafetch", "0011_ministerialmeeting_is_roundtable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="name",
            field=models.CharField(
                help_text="A person or organization's preferred full name",
                max_length=1024,
                verbose_name="name",
            ),
        ),
    ]
