# Generated by Django 6.0.1 on 2026-01-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datafetch", "0012_alter_actor_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="othername",
            name="name",
            field=models.CharField(
                help_text="An alternate or former name", max_length=1024, verbose_name="name"
            ),
        ),
    ]
