# Generated by Django 6.0.1 on 2026-01-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datafetch", "0013_alter_othername_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ministerialmeeting",
            name="external_actor_name_raw",
            field=models.CharField(
                help_text="Preserve original external actor name exactly as published",
                max_length=2048,
            ),
        ),
    ]
