# Generated by Django 6.0.1 on 2026-01-22 00:18

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datafetch", "0014_alter_ministerialmeeting_external_actor_name_raw"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompaniesHouseMatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="creation time",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modification time",
                    ),
                ),
                (
                    "company_number",
                    models.CharField(help_text="Companies House company number", max_length=20),
                ),
                (
                    "company_name",
                    models.CharField(help_text="Company name from Companies House", max_length=500),
                ),
                (
                    "company_status",
                    models.CharField(
                        blank=True,
                        help_text="Company status (active, dissolved, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "company_type",
                    models.CharField(
                        blank=True,
                        help_text="Company type from CH (ltd, plc, llp, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Confidence score (0.0-1.0) based on match quality"
                    ),
                ),
                (
                    "match_reason",
                    models.CharField(help_text="How the match was determined", max_length=30),
                ),
                (
                    "match_details",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of match (e.g., 'Grayling → GRAYLING COMMUNICATIONS LIMITED')",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("auto_approved", "Auto-Approved (High Confidence)"),
                        ],
                        default="pending",
                        help_text="Review status",
                        max_length=15,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, help_text="When this was reviewed", null=True),
                ),
                ("notes", models.TextField(blank=True, help_text="Admin notes")),
                (
                    "enriched",
                    models.BooleanField(
                        default=False,
                        help_text="Whether organization has been enriched with CH data",
                    ),
                ),
                (
                    "enriched_at",
                    models.DateTimeField(
                        blank=True, help_text="When enrichment was applied", null=True
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization to match to Companies House",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies_house_matches",
                        to="datafetch.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this match",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Companies House Match",
                "verbose_name_plural": "Companies House Matches",
                "ordering": ["-confidence", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-confidence"], name="datafetch_c_status_cb000e_idx"
                    ),
                    models.Index(
                        fields=["organization", "status"], name="datafetch_c_organiz_bcb0b9_idx"
                    ),
                    models.Index(fields=["company_number"], name="datafetch_c_company_67af58_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "company_number"), name="unique_org_company_match"
                    )
                ],
            },
        ),
    ]
