# Generated by Django 6.0.1 on 2026-01-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datafetch", "0015_companieshousematch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companieshousematch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("auto_approved", "Auto-Approved (High Confidence)"),
                    ("not_found", "Not Found in Companies House"),
                ],
                default="pending",
                help_text="Review status",
                max_length=15,
            ),
        ),
    ]
