# Generated by Django 6.0.1 on 2026-01-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datafetch", "0017_simplify_ministerialmeeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="companieshousematch",
            name="not_applicable_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("government_dept", "Government Department"),
                    ("local_authority", "Local Authority/Council"),
                    ("university", "University/College"),
                    ("nhs", "NHS/Health Trust"),
                    ("police", "Police Force"),
                    ("trade_union", "Trade Union"),
                    ("trade_body", "Trade Association/Federation"),
                    ("foreign_entity", "Foreign Company/Government"),
                    ("embassy", "Embassy/Consulate"),
                    ("parliamentary", "Parliamentary Body/APPG"),
                    ("person", "Individual Person"),
                    ("concatenated", "Concatenated Names (Data Quality Issue)"),
                    ("other", "Other Non-Registrable Entity"),
                ],
                help_text="Why this org is not CH registrable (only for status='not_applicable')",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="companieshousematch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("auto_approved", "Auto-Approved (High Confidence)"),
                    ("not_found", "Not Found in Companies House"),
                    ("not_applicable", "Not Applicable (Not CH Registrable)"),
                ],
                default="pending",
                help_text="Review status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ministerialmeeting",
            name="organisation_met_raw",
            field=models.CharField(
                help_text="Exact text from GOV.UK 'Organisation Met' column (for audit/dedup)",
                max_length=2048,
            ),
        ),
    ]
