# Generated by Django 6.0.1 on 2026-01-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datafetch", "0018_add_not_applicable_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="companieshousematch",
            name="has_tie",
            field=models.BooleanField(
                default=False,
                help_text="True if multiple CH results had same top confidence (needs manual review)",
            ),
        ),
        migrations.AddField(
            model_name="companieshousematch",
            name="tie_alternatives",
            field=models.JSONField(
                blank=True,
                help_text="Alternative matches when there's a tie. Format: [{company_number, company_name, confidence}, ...]",
                null=True,
            ),
        ),
    ]
