# Generated by Django 6.0.1 on 2026-01-28 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datafetch", "0019_companieshousematch_has_tie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="canonical_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Canonical actor for merged duplicates. If set, this actor is a duplicate.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicate_entries",
                to="datafetch.actor",
            ),
        ),
    ]
